Functions to cache/load files from URL/local paths
pathology-dynamics/biomedical-entity-linking pull request #17
Opened 2024-02-19 20:45 UTC by batuinmetz

This file is exactly similar to the one in the original SciSpacy repository, it is reusable in my case. It may be reusable for other models as it doesn't have any dependencies with Spacy or other SciSpacy files.

2024-03-06 19:36 UTC, davidkartchner requested changes

2024-03-06 19:36 UTC, davidkartchner commented on scispacy/KB_generation.py
Please integrate this into ontology.py to automatically create the needed files from our ontology object.

2024-03-06 19:36 UTC, davidkartchner commented on scispacy/file_cache.py
This similarly needs to be modified to work with `ontology.py` and remove any scispacy specific paths.

2024-03-15 19:00 UTC, prasbathala requested changes
- [ ] Remove SciSpacy specific paths in line 17 and line 18
- [ ] Change the function ```get_from_cache``` to general name: may be ```get_from_url```.
- [ ] Also change the function name ```cached_path``` to ```get_path```

2024-04-03 18:38 UTC, closed without merging