Updating ontology load json
pathology-dynamics/biomedical-entity-linking pull request #33
Opened 2024-04-14 23:04 UTC by batuinmetz

2024-04-16 16:30 UTC, prasbathala reviewed
Overall looks good. Need to test on different functionalities. Once all the unit test cases are in, It can be merged.

2024-04-16 16:30 UTC, prasbathala commented on bioel/tests/test_ontology.py
> +        TestCase - 1: Read from the Json/Jsonl Ontology Directory and check for data formatting issues in the entities.
Can you add some more test cases for the JSON.
1. Give a local path.
2. Give a URL to the dataset.
3. Check if it is already downloaded, and it is accessing from the local cache or not. 
4. check if not downloaded, is it able to download the dataset.

2024-04-16 16:30 UTC, prasbathala commented on bioel/bioel/ontology.py
> +    def load_json(cls, filepath, name=None):
Can you also write a detailed description of what functionalities `load_json` can offer/support?

2024-04-16 16:31 UTC, prasbathala requested changes
Requesting changes for test cases.

2024-06-15 15:34 UTC, batuinmetz reviewed
done

2024-06-15 15:37 UTC, merged